# -*- coding: utf-8 -*-
"""extract_papers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H8nFXJ-no17ojlTo05hlFDT5pblfKALf
"""

!pip install arxiv

import arxiv
import csv


search = arxiv.Search(
    query='"quantum computing"',
    max_results=2000
)
#we re looking for quantum computing as a regular expression

results = list(search.results())

papers = []

#data will contain the first author year of publication and pdf's url
for result in results:
    title = result.title
    authors = [str(author) for author in result.authors]
    first_author = authors[0] if authors else None
    year = result.published.year
    pdf_url = result.pdf_url

    papers.append({"title": title, "first_author": first_author, "year": year,"pdf_url": pdf_url})

import pandas as pd


csv_filename = "papers.csv"
df = pd.read_csv(csv_filename)

df["year"] = pd.to_numeric(df["year"], errors="coerce")

df = df.dropna(subset=["year"])
df["year"] = df["year"].astype(int)


df = df[df["year"] >= 2005]
#we will only keep anything after 2005 and sort in asceniding order

df = df.sort_values(by="year", ascending=False)


filtered_csv_filename = "filtered_papers.csv"
df.to_csv(filtered_csv_filename, index=False)